#lang racket

(provide gen-libwayland-client)

(define template
"#lang racket/base

;;; NOTE: THIS IS AN AUTOGENERATED FILE

(require ffi/unsafe ffi/unsafe/define)

(provide libwayland-client)

(define libwayland-client (ffi-lib \"~alibwayland-client\"))
")

(define (gen-libwayland-client dir)
  (define text (format template dir))
  (call-with-output-file
    "wayland-0/generated/libwayland-client.rkt"
    ((curry display) text)
    #:mode 'text
    #:exists 'replace))
