#lang racket

(provide gen-libwayland-server)

(define template
"#lang racket/base

;;; NOTE: THIS IS AN AUTOGENERATED FILE

(require ffi/unsafe ffi/unsafe/define)

(provide libwayland-server)

(define libwayland-server (ffi-lib \"~alibwayland-server\"))
")

(define (gen-libwayland-server dir)
  (define text (format template dir))
  (call-with-output-file
    "wayland-0/generated/libwayland-server.rkt"
    ((curry display) text)
    #:mode 'text
    #:exists 'replace))
