#lang racket

(provide gen-libc)

(define template
"#lang racket/base

;;; NOTE: THIS IS AN AUTOGENERATED FILE

(require ffi/unsafe ffi/unsafe/define)

(provide strerror)
(define libc (ffi-lib \"~alibc\" \"6\"))
(define-ffi-definer define-libc libc)
(define-libc strerror (_fun _int -> _string/utf-8))
")

;; ISSUE: Debian libc.so is a GNU ld script?"
(define (gen-libc dir)
  (define text (format template dir))
  (call-with-output-file
    "wayland-0/generated/libc.rkt"
    ((curry display) text)
    #:mode 'text
    #:exists 'replace))
